SnapMarket/Areas/Admin/Controllers/FileController.cs
using System;
using System.IO;
using System.Linq;
using System.ComponentModel;
using System.Threading.Tasks;
using System.Collections.Generic;
using AutoMapper;
using ImageMagick;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using SnapMarket.Entities;
using SnapMarket.Data.Contracts;
using SnapMarket.ViewModels.File;
using SnapMarket.Common.Extensions;
using SnapMarket.Common.Attributes;
using SnapMarket.ViewModels.Product;
using SnapMarket.ViewModels.DynamicAccess;

namespace SnapMarket.Areas.Admin.Controllers
{
    [DisplayName("مدیریت فایل ها")]
    public class FileController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _uw;
        private readonly IWebHostEnvironment _env;
        private const string FileNotFound = "فایل درخواستی یافت نشد.";
        public FileController(IUnitOfWork uw, IMapper mapper, IWebHostEnvironment env)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));
            _env = env;
            _env.CheckArgumentIsNull(nameof(_env));
            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }

        [HttpGet, DisplayName("مشاهده"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetFiles(string search, string order, int offset, int limit, string sort)
        {
            List<FileViewModel> viewModels;
            int total = _uw.BaseRepository<FileStore>().CountEntities();

            if (!search.HasValue())
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "تصویر")
            {
                if (order == "asc")
                    viewModels = await _uw.FileRepository.GetPaginateFilesAsync(offset, limit, "ImageName", search);
                else
                    viewModels = await _uw.FileRepository.GetPaginateFilesAsync(offset, limit, "ImageName desc", search);
            }
            else if (sort == "فایل/سند")
            {
                if (order == "asc")
                    viewModels = await _uw.FileRepository.GetPaginateFilesAsync(offset, limit, "FileName", search);
                else
                    viewModels = await _uw.FileRepository.GetPaginateFilesAsync(offset, limit, "FileName desc", search);
            }
            else
                viewModels = await _uw.FileRepository.GetPaginateFilesAsync(offset, limit, "ImageName", search);

            if (search != "")
                total = viewModels.Count();

            return Json(new { total = total, rows = viewModels });
        }

        [HttpGet]
        public IActionResult Upload(string productId)
        {
            return PartialView("UploadMultiImage", new ProductViewModel(productId));
        }

        [HttpPost, Route("Upload")]
        public async Task<IActionResult> UploadPost(IEnumerable<IFormFile> files, string productId)
        {
            try
            {
                //var findDuplicateImage = _uw.BaseRepository<FileStore>().FindByConditionAsync(f => f.ProductId == productId).Result.FirstOrDefault();
                //if(findDuplicateImage != null) return PartialView("UploadMultiImage", new ProductViewModel(productId));
                var uploadsRootFolder = Path.Combine(_env.WebRootPath, "gallery");
                var uploadInAngularFolder = Path.Combine(_env.WebRootPath + "\\..\\..\\Angular\\src\\assets", "gallery");
                if (!Directory.Exists(uploadsRootFolder))
                    Directory.CreateDirectory(uploadsRootFolder);
                if (!Directory.Exists(uploadInAngularFolder))
                    Directory.CreateDirectory(uploadInAngularFolder);

                var nameImages = new List<string>();
                foreach (var item in files)
                {
                    if (item != null)
                    {
                        var fileExtension = Path.GetExtension(item.FileName);
                        var imageName = String.Concat($"product-{productId}-{StringExtensions.GenerateId(10)}", fileExtension);
                        var path = Path.Combine(uploadsRootFolder, imageName);
                        var pathAngular = Path.Combine(uploadInAngularFolder, imageName);
                        using (var memory = new MemoryStream())
                        {
                            await item.CopyToAsync(memory);
                            using (var Image = new MagickImage(memory.ToArray()))
                            {
                                Image.Resize(Image.Width / 2, Image.Height / 2);
                                Image.Quality = 50;
                                Image.Write(path);
                                Image.Write(pathAngular);
                            }
                        }
                        nameImages.Add(imageName);
                        //CompressImage(path);
                    }
                }
                if (nameImages.Count != 0)
                    await _uw.FileRepository.InsertMultiImageAsync(productId, null, null, nameImages);
                return PartialView("UploadMultiImage", new ProductViewModel(new JsonResult("success"), productId));
            }
            catch (Exception e)
            {
                return PartialView("UploadMultiImage", new ProductViewModel(productId));
            }
        }

        private void CompressImage(string path)
        {
            var Image = new FileInfo(path);
            var optimizer = new ImageOptimizer();
            optimizer.Compress(Image); //error
            Image.Refresh();
        }

        [HttpGet, AjaxOnly, DisplayName("حذف"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string fileId)
        {
            if (!fileId.HasValue())
                ModelState.AddModelError(string.Empty, FileNotFound);
            else
            {
                var fileStore = await _uw.BaseRepository<FileStore>().FindByIdAsync(fileId);
                if (fileStore == null)
                    ModelState.AddModelError(string.Empty, FileNotFound);
                else
                    return PartialView("_DeleteConfirmation", fileStore);
            }
            return PartialView("_DeleteConfirmation");
        }

        [HttpPost, ActionName("Delete"), AjaxOnly]
        public async Task<IActionResult> DeleteConfirmed(FileStore model)
        {
            if (!model.ImageName.HasValue())
                ModelState.AddModelError(string.Empty, FileNotFound);
            else
            {
                var fileStore = await _uw.BaseRepository<FileStore>().FindByIdAsync(model.ImageName);
                if (fileStore == null)
                    ModelState.AddModelError(string.Empty, FileNotFound);
                else
                {
                    fileStore.RemoveTime = DateTime.Now;
                    _uw.BaseRepository<FileStore>().Update(fileStore);
                    await _uw.Commit();
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation", fileStore);
                }
            }
            return PartialView("_DeleteConfirmation");
        }

        [HttpPost, ActionName("DeleteGroup"), AjaxOnly, DisplayName("حذف گروهی"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ فایلی برای حذف انتخاب نشده است.");
            else
            {
                var splited = new string[btSelectItem.Length];
                foreach (var item in btSelectItem)
                    splited = item.Split(',');

                foreach (var splite in splited)
                {
                    var file = await _uw.BaseRepository<FileStore>().FindByIdAsync(int.Parse(splite));
                    file.RemoveTime = DateTime.Now;
                    _uw.BaseRepository<FileStore>().Update(file);
                }
                await _uw.Commit();
                return Ok(DeleteGroupSuccess);
            }
            return BadRequest(FileNotFound);
        }
    }
}

SnapMarket/Areas/Admin/Views/File/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "../Shared/_AdminLayout.cshtml";
}

<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="/Admin/Dashboard/Index"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="/Admin/File/Index">مدیریت فایل ها</a>
            </li>
        </ul>
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>

<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8"></div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                مدیریت فایل ها
            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="File">
                    @await Html.PartialAsync("_FileTable")
                </form>
            </div>
        </div>
    </div>
</div>

SnapMarket/Areas/Admin/Views/File/UploadMultiImage.cshtml
@model SnapMarket.ViewModels.Product.ProductViewModel

<link href="~/lib/fileUpload/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
<link href="~/lib/fileUpload/themes/explorer-fas/theme.css" media="all" rel="stylesheet" type="text/css" />
<script src="~/lib/fileUpload/js/plugins/piexif.js" type="text/javascript"></script>
<script src="~/lib/fileUpload/js/plugins/sortable.js" type="text/javascript"></script>
<script src="~/lib/fileUpload/js/fileinput.js" type="text/javascript"></script>
<script src="~/lib/fileUpload/js/locales/fr.js" type="text/javascript"></script>
<script src="~/lib/fileUpload/js/locales/es.js" type="text/javascript"></script>
<script src="~/lib/fileUpload/themes/fas/theme.js" type="text/javascript"></script>
<script src="~/lib/fileUpload/themes/explorer-fas/theme.js" type="text/javascript"></script>

<style>
    .modal-dialog {
        max-width: 800px !important;
    }
</style>

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">
                    انتخاب چند تصویر برای محصول
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form asp-action="Upload" enctype="multipart/form-data">
                    <input type="hidden" id="productId" name="productId" value="@Model.Id" class="center-block" />
                    <div class="file-loading">
                        <input id="kv-explorer" name="files" type="file" data-browse-on-zone-click="true" multiple>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>

<script>
    //$(document).ready(function () {
    //    debugger
    //    var file1 = document.getElementById('file1');
    //    var file = document.getElementsByTagName('file-input file-input-ajax-new');
    //    file1.remove();
    //});

    $(document).ready(function () {
        $("#kv-explorer").fileinput({
            //'theme': 'fas',
            'theme': 'explorer-fas',
            overwriteInitial: false,
            initialPreviewAsData: true,
            uploadUrl: "/Upload",
            //uploadAsync: false,
            //minFileCount: 5,
            maxFileCount: 5,
            maxFileSize: 80000,
            maxFilesNum: 10,
            allowedFileExtensions: ['jpg', 'png', 'gif'],
            allowedFileTypes: ['image'],
            uploadExtraData: function () {
                return {
                    productId: $("#productId").val(),
                };
            }
        });
    });
</script>

SnapMarket/Areas/Admin/Views/File/_DeleteConfirmation.cshtml
@model SnapMarket.Entities.FileStore

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">حذف فایل</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body clearfix">
                @if (Model == null)
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما می خواهید این فایل را حذف کنید ؟</h4>
                    <form asp-action="Delete">
                        <input name="IsValid" type="hidden" value="True" />
                        <input type="hidden" asp-for="ImageName" />
                    </form>
                }
            </div>
            <div class="modal-footer">
                @if (Model != null)
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                        بله
                    </button>
                }
                <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                    @(Model != null ? "خیر" : "بستن")
                </button>
            </div>
        </div>
    </div>
</div>