SnapMarket/Areas/Admin/Controllers/SellerController.cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.ComponentModel;
using System.Threading.Tasks;
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using SnapMarket.Entities;
using SnapMarket.ViewModels;
using SnapMarket.Data.Contracts;
using SnapMarket.Common.Extensions;
using SnapMarket.ViewModels.Product;
using SnapMarket.ViewModels.DynamicAccess;

namespace SnapMarket.Areas.Admin.Controllers
{
    [DisplayName("مدیریت فروشندگان")]
    public class SellerController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _uw;
        private readonly IWebHostEnvironment _env;
        private readonly IHttpContextAccessor _context;
        private const string ProductNotFound = "محصول یافت نشد.";
        private const string SellerNotFound = "فروشنده یافت نشد.";
        public SellerController(IUnitOfWork uw, IMapper mapper, IWebHostEnvironment env, IHttpContextAccessor context)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));
            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
            _env = env;
            _env.CheckArgumentIsNull(nameof(_env));
            _context = context;
            _context.CheckArgumentIsNull(nameof(_context));
        }

        [HttpGet, DisplayName("مشاهده"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetSellers(string search, string order, int offset, int limit, string sort)
        {
            List<SellerViewModel> viewModels;
            int total = _uw.BaseRepository<Seller>().CountEntities();

            if (!search.HasValue())
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "brand")
            {
                if (order == "asc")
                    viewModels = await _uw.SellerRepository.GetPaginateSellersAsync(offset, limit, "Brand", search);
                else
                    viewModels = await _uw.SellerRepository.GetPaginateSellersAsync(offset, limit, "Brand desc", search);
            }
            else if (sort == "userVote")
            {
                if (order == "asc")
                    viewModels = await _uw.SellerRepository.GetPaginateSellersAsync(offset, limit, "UserVote", search);
                else
                    viewModels = await _uw.SellerRepository.GetPaginateSellersAsync(offset, limit, "UserVote desc", search);
            }
            else if (sort == "persianRegisterDate")
            {
                if (order == "asc")
                    viewModels = await _uw.SellerRepository.GetPaginateSellersAsync(offset, limit, "RegisterDate", search);
                else
                    viewModels = await _uw.SellerRepository.GetPaginateSellersAsync(offset, limit, "RegisterDate desc", search);
            }
            else
                viewModels = await _uw.SellerRepository.GetPaginateSellersAsync(offset, limit, "RegisterDate desc", search);

            if (search != "")
                total = viewModels.Count();

            return Json(new { total = total, rows = viewModels });
        }

        [HttpGet, DisplayName("درج و ویرایش"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> CreateOrUpdate(int sellerId)
        {
            var viewModel = new SellerViewModel();
            if (sellerId == 0)
                ModelState.AddModelError(string.Empty, SellerNotFound);
            else
            {
                var seller = await _uw.BaseRepository<Seller>().FindByIdAsync(sellerId);
                if (seller != null)
                {
                    viewModel = _mapper.Map<SellerViewModel>(seller);
                    var store = await _uw.Context.Stores.FirstOrDefaultAsync(s => s.SellerId == seller.Id);
                    if (store != null)
                    {
                        viewModel.Store = store.Name;
                        viewModel.Address = store.Address;
                        viewModel.TelNumber = store.TelNumber;
                        viewModel.PostalCode = store.PostalCode;
                        viewModel.SampleProduct = store.Description;
                        viewModel.PersianEstablishmentDate = store.EstablishmentDate.ConvertMiladiToShamsi("yyyy/MM/dd");
                    }
                    if (seller.InsertTime > DateTime.Now)
                    {
                        viewModel.PersianInsertTime = seller.InsertTime.ConvertMiladiToShamsi("yyyy/MM/dd");
                        viewModel.PersianInsertTime = seller.InsertTime.Value.TimeOfDay.ToString();
                    }

                    if (seller.InsertTime > DateTime.Now)
                        viewModel.PersianInsertTime = seller.InsertTime.ConvertMiladiToShamsi("yyyy/MM/dd");
                }
                else
                    ModelState.AddModelError(string.Empty, SellerNotFound);
            }
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(SellerViewModel viewModel)
        {
            if (viewModel.Id != 0)
            {
                ModelState.Remove("SellerImageFile");
                ModelState.Remove("NationalIdImageFile");
                ModelState.Remove("DocumentImageFile");
            }
            if (ModelState.IsValid)
            {
                if (viewModel.Id != 0)
                {
                    var lastImages = await _uw.FileRepository.GetImagesAsync(null, viewModel.Id, null);
                    if (viewModel.SellerImageFile != null)
                        await ImageManager(null, viewModel.SellerImageFile, viewModel.Id, lastImages);
                    if (viewModel.NationalIdImageFile != null)
                        await ImageManager(null, viewModel.NationalIdImageFile, viewModel.Id, null);
                    if (viewModel.DocumentImageFile.HasValue())
                        await ImageManager(viewModel.DocumentImageFile, null, viewModel.Id, null);

                    var seller = await _uw.BaseRepository<Seller>().FindByIdAsync(viewModel.Id);
                    if (seller == null)
                        ModelState.AddModelError(string.Empty, SellerNotFound);
                    else
                    {
                        viewModel.UpdateTime = DateTime.Now;
                        _uw.BaseRepository<Seller>().Update(_mapper.Map(viewModel, seller));

                        var store = await _uw.BaseRepository<Store>().FindByConditionAsync(s => s.Name == viewModel.Store && s.PostalCode == viewModel.PostalCode);
                        if (store.Count() != 0)
                        {
                            store.FirstOrDefault().Name = viewModel.Store;
                            store.FirstOrDefault().Address = viewModel.Address;
                            store.FirstOrDefault().TelNumber = viewModel.TelNumber;
                            store.FirstOrDefault().PostalCode = viewModel.PostalCode;
                            store.FirstOrDefault().Description = viewModel.SampleProduct;
                            store.FirstOrDefault().EstablishmentDate = viewModel.PersianEstablishmentDate.ConvertShamsiToMiladi();
                            store.FirstOrDefault().UpdateTime = DateTimeExtensions.DateTimeWithOutMilliSecends(DateTime.Now);
                            _uw.BaseRepository<Store>().Update(store.FirstOrDefault());
                        }
                        else if (viewModel.Store.HasValue())
                        {
                            var newStore = new Store
                            {
                                Id = viewModel.Id,
                                Name = viewModel.Store,
                                SellerId = viewModel.Id,
                                Address = viewModel.Address,
                                TelNumber = viewModel.TelNumber,
                                PostalCode = viewModel.PostalCode,
                                Description = viewModel.SampleProduct,
                                EstablishmentDate = viewModel.PersianEstablishmentDate.ConvertShamsiToMiladi(),
                                InsertTime = DateTimeExtensions.DateTimeWithOutMilliSecends(DateTime.Now)
                            };
                            await _uw.BaseRepository<Store>().CreateAsync(newStore);
                        }
                        await _uw.Commit();
                        ViewBag.Alert = EditSuccess;
                    }
                }
                else
                {
                    var maxSeller = new Seller();
                    var sellers = await _uw.BaseRepository<Seller>().FindAllAsync();
                    if (sellers.Count() != 0)
                        maxSeller = sellers.OrderByDescending(c => c.Id).FirstOrDefault();

                    viewModel.InsertTime = DateTime.Now;
                    viewModel.Id = sellers.Count() == 0 ? 1 : maxSeller.Id + 1;
                    await _uw.BaseRepository<Seller>().CreateAsync(_mapper.Map<Seller>(viewModel));
                    await _uw.Commit();

                    if (viewModel.Store.HasValue())
                    {
                        var newStore = new Store
                        {
                            Id = viewModel.Id,
                            Name = viewModel.Store,
                            SellerId = viewModel.Id,
                            Address = viewModel.Address,
                            TelNumber = viewModel.TelNumber,
                            PostalCode = viewModel.PostalCode,

SnapMarket/Areas/Admin/Views/Seller/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "../Shared/_AdminLayout.cshtml";
}

<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="/Admin/Dashboard/Index"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="/Admin/Seller/Index">مدیریت فروشندگان </a>
            </li>
        </ul>
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8"></div>
<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                مدیریت فروشندگان
            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="Seller">
                    @await Html.PartialAsync("_SellerTable")
                </form>
            </div>
        </div>
    </div>
</div>

SnapMarket/Areas/Admin/Views/Seller/ProductsOfSeller.cshtml
@model SnapMarket.ViewModels.Product.ProductViewModel
@{
    ViewData["Title"] = "ProductsOfSeller";
    Layout = "../Shared/_AdminLayout.cshtml";
}

<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="/Admin/Dashboard/Index"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="/Admin/Seller/ProductsOfSeller?sellerId=@Model.SellerId&isSeller=false">نمایش محصولات </a>
            </li>
        </ul>
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8"></div>
<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            @if (Model.IsSeller == false)
            {
                <div class="card-header font_Vazir_Medium">
                    افزودن محصولات
                </div>
            }
            else
            {
                <div class="card-header font_Vazir_Medium">
                    محصولات فروشنده
                </div>
            }
            <div class="card-body">
                @if (ViewBag.Alert != null)
                {
                    <div class="col-md-12">
                        <div class="alert alert-danger mb-4 alert-dismissable">
                            @ViewBag.Alert
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                }
                @if (ViewBag.Success != null)
                {
                    <div class="col-md-12">
                        <div class="alert alert-success mb-4 alert-dismissable">
                            @ViewBag.Success
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                }
                <form asp-area="Admin" asp-controller="Product">
                    <div id="toolbar">
                        @if (Model.IsSeller == false)
                        {
                            <button type="button" id="add" class="btn btn-info" onclick="AddProductGroupToSeller('@Model.SellerId', getIdSelections())" disabled>
                                <i class="fab fa-plus-square"></i> | افزودن گروهی محصولات به فروشنده
                            </button>
                            <button type="button" class="btn btn-outline-light" onclick="ShowProductSeller('@Model.SellerId')" id="@Model.SellerId">
                                <i class="fab fa-adversal"></i> | مشاهده محصولات فروشنده
                            </button>
                        }
                        else
                        {
                            <button type="button" id="remove" class="btn btn-danger" onclick="DeleteGroupProduct('Seller', getIdSelections())" disabled>
                                <i class="fa fa-trash"></i> | حذف گروهی
                            </button>
                            <button type="button" class="btn btn-outline-info text-gray-dark" onclick="ShowAllProduct('@Model.SellerId')" id="@Model.SellerId">
                                <i class="fas fa-store-alt text-gray-dark"></i> | مشاهده محصولات باقی مانده
                            </button>
                        }
                    </div>
                    <table id="table"
                           data-toolbar="#toolbar"
                           data-search="true"
                           data-show-refresh="true"
                           data-show-toggle="true"
                           data-show-fullscreen="true"
                           data-show-columns="true"
                           data-show-columns-toggle-all="false"
                           data-detail-view="true"
                           data-show-export="true"
                           data-click-to-select="false"
                           data-detail-formatter="detailFormatter"
                           data-minimum-count-columns="2"
                           data-show-pagination-switch="true"
                           data-pagination="true"
                           data-id-field="id"
                           data-page-list="[10, 25, 50, 100, all]"
                           data-show-footer="true"
                           data-side-pagination="server"
                           data-url="/Admin/Seller/GetProductsForSeller?sellerId=@Model.SellerId&isSeller=@Model.IsSeller"
                           data-response-handler="responseHandler">
                    </table>

                    <script>
    var $table = $('#table');
    var $add = $('#add');
    var $remove = $('#remove');
    var selections = [];
    var SellerProductIds = [];

    function get_query_params(p) {
        return {
            extraParam: 'abc',
            search: p.title,
            sort: p.sort,
            order: p.order,
            limit: p.limit,
            offset: p.offset
        }
    }

    function responseHandler(res) {
        $.each(res.rows, function (i, row) {
            row.state = $.inArray(row.id, selections) !== -1
        })
        return res
    }

    function getIdSelections() {
        return $.map($table.bootstrapTable('getSelections'), function (row) {
            return sellerProductIds = row.Id;
        })
    }

    function detailFormatter(index, row) {
        var html = []
        $.each(row, function (key, value) {
            if (key != "state" && key != "Id" && key != "ردیف" && key != "barcode" && key != "states" && key != "percentDiscount" &&  key != "imageFiles" && key != "imageName" && key != "stock" && key != "price" && key != "isPresent" && key != "productState" && key != "nameOfCategories" && key != "shortName" && key != "insertTime" && key != "isPrefered" && key != "isComplete" && key != "expirationDate") {
                if (key == "weight") key = 'وزن';
                if (key == "madeIn") key = 'ساخت';
                if (key == "name") key = 'نام محصول';
                if (key == "nameOfBrand") key = 'برند';
                if (key == "size") key = 'ابعاد/اندازه';
                if (key == "displayStates") key = 'وضعیت';
                if (key == "displayDiscount") key = 'تخفیف';
                if (key == "numberOfVisit") key = 'بازدید ها';
                if (key == "numberOfComments") key = 'کامنت ها';
                if (key == "actionDiscount") key = 'محاسبه تخفیف';
                if (key == "persianExpirationDate") key = 'تاریخ انقضا';
                if (key == "persianInsertTime") key = 'تاریخ ساخت/تولید';

                if (key == "numberOfSale") {
                    key = 'تعداد کل سفارش داده شده از این محصول';
                    if (value == null || value == '')
                        value = '0'
                }
                if (key == "color") {
                    key = 'رنگ اصلی';
                    if (value == null || value == '')
                        value = 'بی رنگ'
                }
                if (key == "description") {
                    key = 'توضیحات';
                    if (value == null || value == '')
                        value = 'ندارد'
                }
                if (key == 'guarantee') {
                    key = 'ضمانت/گارانتی';
                    if (value == null || value == '')
                        value = 'ندارد'
                }
                if (key == 'nameOfSeller') {
                    key = 'نام فروشنده محصول';
                    if (value == null || value == '')
                        value = '<span class="badge badge-danger">این محصول قروشنده ندارد!</span>'
                    else
                        value = '<span class="badge badge-light">' + value + '</span>'
                }
                if (key == 'displayPrice') {
                    key = 'قیمت مصرف کننده';
                    value = row.displayPrice + ' <small>(ریال)</small> ';
                }
                html.push('<p><b>' + key + ':</b> ' + value + '</p>')
            }
            if (key == "barcode") {
                key = 'QRCode';
                if (value != null) {
                    html.push('<p><b>' + key + ':</b> <img src="data:image/png;base64,' + value + '" height="200" width="200" /></p>')
                }
                else {
                    value = '';
                    html.push('<p><b>' + key + ':</b> ' + value + '</p>')
                }
            }
            if (key == "imageName") {
                key = 'تصویر محصول';
                if (value != null) {
                    var url = '@string.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)' + '/images/' + value;
                    html.push('<p><b>' + key + ':</b> <img src="' + url + '" height="200" /></p>')
                }
            }
        })
        return html.join('')
    }

    function operateFormatter(value, row, index) {
        var access = "";
        if ('@Model.IsSeller' == 'False') {
            access = access + '<button type="button" class="btn-link text-info" onclick="AddProductToStore(' + "'" + row.Id + "'" + ",'" + @Model.SellerId + "'" + ')" id="' + row.Id + '" title="افزودن به فروشگاه"><i class="fa fa-store"></i></button >';
        }
        if ('@Model.IsSeller' == 'True') {
            access = access + '<button type="button" class="btn-link text-danger" data-toggle="ajax-modal" data-url=@Url.Action("DeleteOfStore", "Seller")?sellerId=' + @Model.SellerId + '&productId=' + row.Id + ' title="حذف از فروشگاه"><i class="fa fa-trash"></i></button >';
        }
        return access;
    }

    function stockFormatter(value, row, index) {
        return [
            '<a class="btn btn-danger btn-sm text-white">',
            row.stock,
            '</a >'
        ].join('')
    }

    function totalTextFormatter(data) {
        return 'تعداد'
    }

    function totalNameFormatter(data) {
        return data.length
    }

    function initTable() {
        $table.bootstrapTable('destroy').bootstrapTable({
            height: 600,
            locale: 'fa-IR',
            columns: [
                [{
                    field: 'state',
                    checkbox: true,
                    rowspan: 2,
                    align: 'center',
                    valign: 'middle',
                    name: 'getSelections'
                },{
                    title: 'ردیف',
                    field: 'ردیف',
                    rowspan: 2,
                    align: 'center',
                    valign: 'middle',
                    footerFormatter: totalTextFormatter
                },{
                    title: 'جزئیات اطلاعات محصولات',
                    colspan: 6,
                    align: 'center'
                }],
                [{
                    field: 'name',
                    title: 'محصول',
                    sortable: true,
                    footerFormatter: totalNameFormatter
                },{
                    field: 'nameOfCategories',
                    title: 'دسته',
                    sortable: false,
                    align: 'center'
                },{
                    field: 'displayPrice',
                    title: 'قیمت<small>(تومان)</small>',
                    sortable: true,
                    align: 'center',
                },{
                    field: 'stock',
                    title: 'موجودی',
                    sortable: true,
                    align: 'center',
                    formatter: stockFormatter
                },{
                    field: 'persianInsertTime',
                    title: 'تاریخ تولید',
                    sortable: true,
                    align: 'center'
                },{
                    field: 'operate',
                    title: 'عملیات',
                    align: 'center',
                    formatter: operateFormatter
                }]
            ]
        })

        $table.on('check.bs.table uncheck.bs.table ' +
            'check-all.bs.table uncheck-all.bs.table',
            function () {
                $add.prop('disabled', !$table.bootstrapTable('getSelections').length)
                selections = getIdSelections()
            });

        $table.on('check.bs.table uncheck.bs.table ' +
            'check-all.bs.table uncheck-all.bs.table',
            function () {
                $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)
                selections = getIdSelections()
            });
    }

    $(function () {
        initTable()
        $('#locale').change(initTable)
    })
                    </script>

                </form>
            </div>
        </div>
    </div>
</div>

SnapMarket/Areas/Admin/Views/Seller/_AddGroup.cshtml
<div class="modal fade" id="AddGroup" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">افزودن گروهی</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                @{var IsValid = ViewData.ModelState.IsValid.ToString();}
                <input name="IsValid" type="hidden" value="@IsValid" />
                @if (IsValid == "False")
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما میخواهید موارد انتخاب شده را به فروشنده مورد نظر اضافه کنید؟</h4>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-labeled  btn-danger" data-dismiss="modal">
                    @(IsValid == "True" ? "خیر" : "بستن")
                </button>
                @if (IsValid == "True")
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success mr-1" data-save="modal">
                        بله
                    </button>
                }
            </div>
        </div>
    </div>
</div>

SnapMarket/Areas/Admin/Views/Seller/_DeleteConfirmation.cshtml
@model SnapMarket.Entities.Seller

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">حذف فروشنده</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body clearfix">
                @if (Model == null)
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما می خواهید فروشنده "@Model.Name"  را حذف کنید ؟</h4>
                    <form asp-action="Delete">
                        <input name="IsValid" type="hidden" value="True" />
                        <input type="hidden" asp-for="Id" />
                    </form>
                }
            </div>

            <div class="modal-footer">
                @if (Model != null)
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                        بله
                    </button>
                }
                <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                    @(Model != null ? "خیر" : "بستن")
                </button>
            </div>
        </div>
    </div>
</div>

SnapMarket/Areas/Admin/Views/Seller/_DeleteOfStoreConfirmation.cshtml
@model SnapMarket.Entities.Product

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">حذف محصول</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body clearfix">
                @if (Model == null)
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما می خواهید محصول "@Model.Name"  رااز لیست محصولات فروشگاه خود حذف کنید ؟</h4>
                    <form asp-action="DeleteOfStore">
                        <input name="IsValid" type="hidden" value="True" />
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" asp-for="SellerId" />
                    </form>
                }
            </div>

            <div class="modal-footer">
                @if (Model != null)
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                        بله
                    </button>
                }
                <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                    @(Model != null ? "خیر" : "بستن")
                </button>
            </div>
        </div>
    </div>
</div>